name: Deploy

on:
  push:
    branches:
      - lab-4

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - run: mkdir -p ~/.ssh/
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private.key
      - run: chmod 600 ~/.ssh/private.key
      - run: ssh -i ~/.ssh/private.key -o StrictHostKeyChecking=no ubuntu@89.208.222.44 whoami
